// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



class DefaultFirebaseOptions {



  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz1js4EnVHP1St6QAcmhebk6WrF4NcJqY',
    appId: '1:1058895914101:web:f661d0aca194469151443c',
    messagingSenderId: '1058895914101',
    projectId: 'socialappmark1-b6139',
    authDomain: 'socialappmark1-b6139.firebaseapp.com',
    storageBucket: 'socialappmark1-b6139.appspot.com',
    measurementId: 'G-0P3GK8PXHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaRxwNsWS_8r28KniECt9QrlNh4kyovYE',
    appId: '1:1058895914101:android:00278ff6a7649bc751443c',
    messagingSenderId: '1058895914101',
    projectId: 'socialappmark1-b6139',
    storageBucket: 'socialappmark1-b6139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABi5z5m6nZ_FCFDdg4Iv9evAH2MEQ7lvA',
    appId: '1:1058895914101:ios:1eb92f92c465a86051443c',
    messagingSenderId: '1058895914101',
    projectId: 'socialappmark1-b6139',
    storageBucket: 'socialappmark1-b6139.appspot.com',
    iosBundleId: 'com.ub.purdueSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABi5z5m6nZ_FCFDdg4Iv9evAH2MEQ7lvA',
    appId: '1:1058895914101:ios:1eb92f92c465a86051443c',
    messagingSenderId: '1058895914101',
    projectId: 'socialappmark1-b6139',
    storageBucket: 'socialappmark1-b6139.appspot.com',
    iosBundleId: 'com.ub.purdueSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz1js4EnVHP1St6QAcmhebk6WrF4NcJqY',
    appId: '1:1058895914101:web:88277231596cd3e951443c',
    messagingSenderId: '1058895914101',
    projectId: 'socialappmark1-b6139',
    authDomain: 'socialappmark1-b6139.firebaseapp.com',
    storageBucket: 'socialappmark1-b6139.appspot.com',
    measurementId: 'G-F3X667PL9N',
  );
}